[package]
name = "abbs-meta-apml"
version = "0.1.0"
authors = ["Leo Shen <i@szclsya.me>", "liushuyu <liushuyu011@gmail.com>", "zrah <zrah@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
regex = "1"
annotate-snippets = "0.12"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
anyhow = "1"
walkdir = "*"
