[package]
name = "deb-libsolv-resolver"
version = "0.1.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Debian libsolv resolver"

[dependencies]
libsolv-sys = "0.1"
anyhow = "1"
libc = "0.2"
defaultmap = "0.5"
hex = "0.4"
